#-------------------------------
# General Site Settings
title: Apuntes libres

logo: logo.png # You can add own logo.
description: Una página web para publicar apuntes libres de informática aka Ciencias de la Computación

#-------------------------------
# Author Settings
author:
  name: Christian V.
  image: 01.jpg
  say-hello: Hola, soy <strong>Christian V.</strong>
  bio: Escribe sobre <strong>web</strong>, <strong>ética</strong>, <strong>privacidad</strong> y desarrollo de aplicaciones. Comparto tutoriales, recursos gratuitos, recursos educativos. Ama la <a href="#"> música </a> y monta su bicicleta.

follow: Sígueme

#-------------------------------
# Contact links
twitter: https://twitter.com/chvermat # Add your Twitter handle
github: https://github.com/chverma # Add your Github handle
# facebook: https://facebook.com/ # Add your Facebook handle
# dribbble: https://dribbble.com/ # Add your Dribbble handle
# instagram: https://instagram.com/ # Add your Instagram handle
# pinterest: https://pinterest.com/ # Add your Pinterest handle



#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
