#-------------------------------
# General Site Settings
title:
  en: Share 4 teach
  es: Compartir para enseñar
  ca: Compartir per a ensenyar

logo: logo.png # You can add own logo.
description: A website to publish my own content

#-------------------------------
# Author Settings
author:
  name: Christian V.
  image: 01.jpg
  say-hello:
    en: Hello, I’m <strong>Christian V.</strong>
    es: Hola, soy <strong>Christian V.</strong>
    ca: Hola, sóc <strong>Christian V.</strong>
  bio:
    en: Writes about <strong>web</strong>, <strong>ethics</strong>, <strong>privacy</strong>, and dev. I share tutorials, free resources, education resources. Loves <a href="#">music</a> & riding his bike.
    es: Escribe sobre <strong>web</strong>, <strong>ética</strong>, <strong>privacidad</strong> y desarrollo de aplicaciones. Comparto tutoriales, recursos gratuitos, recursos educativos. Ama la <a href="#"> música </a> y monta su bicicleta.
    ca: Escriu sobre <strong>web</strong>, <strong>ètica</strong>, <strong>privadesa</strong> i desenvolupament d'aplicacions. Compartisc tutorials, recursos gratuïts, recursos educatius. Li encanta <a href="#"> la música </a> i anar amb la bicicleta.

follow:
  en: Follow Me
  es: Sígueme
  ca: Segueix-me


#-------------------------------
# Contact links
twitter: https://twitter.com/chvermat # Add your Twitter handle
github: https://github.com/chverma # Add your Github handle
# facebook: https://facebook.com/ # Add your Facebook handle
# dribbble: https://dribbble.com/ # Add your Dribbble handle
# instagram: https://instagram.com/ # Add your Instagram handle
# pinterest: https://pinterest.com/ # Add your Pinterest handle



#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
